name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Setu Up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dhanifajar15/travello-backend:latest
    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          bash /home/dhanifajar15/docker/deploy-backend.sh
